export enum FuncionalStage {
    SAUDACAO = 'SAUDACAO',
    CONSULTAR_AGENDAMENTOS = 'CONSULTAR_AGENDAMENTOS',
    CRIAR_AGENDAMENTO = 'CRIAR_AGENDAMENTO',
    CANCELAR_AGENDAMENTO = 'CANCELAR_AGENDAMENTO',
}

export enum SistemicaStage {
    NAO_ENTENDI = 'NAO_ENTENDI',
    DESPEDIDA = 'DESPEDIDA',
}

export enum ConversationStage {
    SAUDACAO = 'SAUDACAO',
    CONSULTAR_AGENDAMENTOS = 'CONSULTAR_AGENDAMENTOS',
    CRIAR_AGENDAMENTO = 'CRIAR_AGENDAMENTO',
    CANCELAR_AGENDAMENTO = 'CANCELAR_AGENDAMENTO',
    NAO_ENTENDI = 'NAO_ENTENDI',
    DESPEDIDA = 'DESPEDIDA',
}