export enum ActionType {
  CONSULTAR_AGENDAMENTOS = "CONSULTAR_AGENDAMENTOS",
  CRIAR_AGENDAMENTO = "CRIAR_AGENDAMENTO",
  CANCELAR_AGENDAMENTO = "CANCELAR_AGENDAMENTO",
  ATENDIMENTO = "ATENDIMENTO",
  RESPONDER = "RESPONDER",
}